options = [
    {
        'train_processes': ['IntelSoftwareAssetManagerService.exe', 'cmd.exe', 'Explorer.EXE',
            'svchost.exe', 'AxCrypt.exe', 'MFVideoChat2.exe', 'sdclt.exe', 'services.exe',
             'steam.exe', 'DeviceDisplayObjectProvider.exe', 'VBoxService.exe',
             'PT-BulletPhysics64.exe', 'System', 'WMIADAP.EXE', 'Dwm.exe', 'ffmpeg.exe',
             'taskeng.exe', 'lsm.exe', 'VBoxTray.exe', 'SearchIndexer.exe',
             'WordProcessing.exe', 'SearchFilterHost.exe', 'EXCEL.EXE', 'spoolsv.exe',
             'AUDIODG.EXE', 'Cobian.Reflector.Application.exe', 'schtasks.exe',
             'SearchProtocolHost.exe', 'WinRAR.exe', 'DiagTrackRunner.exe', 'helper.exe',
             'wininit.exe', 'PerformanceTest64.exe', 'sc.exe', 'wmiprvse.exe',
             'winlogon.exe', 'GoogleCrashHandler.exe', 'NativeApp.exe', 'lsass.exe',
             'conhost.exe', 'WINWORD.EXE', 'csrss.exe', 'compattelrunner.exe',
             'MFPlayback.exe', 'GoogleUpdate.exe', '7zG.exe', 'sppsvc.exe',
             'PT-CPUTest64.exe', 'Browsing.exe'],
            'test_processes': [
                'CompatTelRunner.exe', 'smss.exe', 'wmpnetwk.exe', 'curl.exe', 'wsqmcons.exe', 'powershell.exe',
                'lame.exe','DllHost.exe', 'GoogleCrashHandler64.exe', 'Idle', 'taskhost.exe', 'libreofficeCalcTest.exe',
                'soffice.bin']
    },
    {
        'train_processes': ['CompatTelRunner.exe', 'libreofficeCalcTest.exe', 'WinRAR.exe',
             'winlogon.exe', 'wininit.exe', 'DeviceDisplayObjectProvider.exe',
             'Explorer.EXE', 'SearchProtocolHost.exe', 'sc.exe', 'SearchIndexer.exe',
             'AUDIODG.EXE', 'services.exe', 'lame.exe', 'WordProcessing.exe',
             'DllHost.exe', 'SearchFilterHost.exe', 'GoogleUpdate.exe', 'svchost.exe',
             'conhost.exe', 'AxCrypt.exe', 'WMIADAP.EXE',
             'Cobian.Reflector.Application.exe', 'NativeApp.exe', 'lsm.exe',
             'Browsing.exe', 'PT-CPUTest64.exe', '7zG.exe', 'DiagTrackRunner.exe',
             'soffice.bin', 'MFPlayback.exe', 'WINWORD.EXE', 'smss.exe',
             'IntelSoftwareAssetManagerService.exe', 'compattelrunner.exe',
             'PerformanceTest64.exe', 'ffmpeg.exe', 'powershell.exe', 'MFVideoChat2.exe',
             'spoolsv.exe', 'VBoxService.exe', 'wsqmcons.exe', 'System', 'sdclt.exe',
             'wmpnetwk.exe', 'GoogleCrashHandler64.exe', 'taskhost.exe', 'lsass.exe',
             'PT-BulletPhysics64.exe', 'Dwm.exe'],
        'test_processes': ['Idle', 'sppsvc.exe', 'VBoxTray.exe', 'csrss.exe', 'wmiprvse.exe', 'steam.exe',
                           'schtasks.exe', 'taskeng.exe', 'GoogleCrashHandler.exe', 'EXCEL.EXE', 'cmd.exe', 'curl.exe',
                           'helper.exe']
    },
    {
        'train_processes': ['Idle', 'powershell.exe', 'taskhost.exe', 'lsass.exe', 'steam.exe', '7zG.exe',
             'DeviceDisplayObjectProvider.exe', 'Dwm.exe',
             'IntelSoftwareAssetManagerService.exe', 'spoolsv.exe',
             'GoogleCrashHandler.exe', 'PT-BulletPhysics64.exe', 'soffice.bin',
             'taskeng.exe', 'Cobian.Reflector.Application.exe', 'curl.exe', 'wininit.exe',
             'WinRAR.exe', 'svchost.exe', 'WINWORD.EXE', 'WordProcessing.exe',
             'DllHost.exe', 'WMIADAP.EXE', 'GoogleUpdate.exe', 'System',
             'SearchProtocolHost.exe', 'AxCrypt.exe', 'PerformanceTest64.exe',
             'sppsvc.exe', 'services.exe', 'MFPlayback.exe', 'helper.exe', 'smss.exe',
             'sc.exe', 'VBoxService.exe', 'AUDIODG.EXE', 'MFVideoChat2.exe', 'csrss.exe',
             'GoogleCrashHandler64.exe', 'SearchIndexer.exe', 'schtasks.exe',
             'NativeApp.exe', 'DiagTrackRunner.exe', 'libreofficeCalcTest.exe',
             'wsqmcons.exe', 'CompatTelRunner.exe', 'cmd.exe', 'VBoxTray.exe', 'wmiprvse.exe'],
        'test_processes': ['sdclt.exe', 'lame.exe', 'SearchFilterHost.exe', 'ffmpeg.exe', 'Explorer.EXE',
                           'wmpnetwk.exe', 'PT-CPUTest64.exe', 'EXCEL.EXE', 'winlogon.exe', 'conhost.exe',
                           'compattelrunner.exe', 'Browsing.exe', 'lsm.exe']
    },
    {
        'train_processes': ['services.exe', 'libreofficeCalcTest.exe', 'Browsing.exe', 'ffmpeg.exe',
             'CompatTelRunner.exe', 'SearchFilterHost.exe', 'wininit.exe', 'smss.exe',
             'Dwm.exe', 'GoogleUpdate.exe', 'helper.exe', 'winlogon.exe', 'curl.exe',
             'lsass.exe', 'MFVideoChat2.exe', 'PerformanceTest64.exe',
             'GoogleCrashHandler.exe', 'Idle', 'sdclt.exe', 'conhost.exe',
             'SearchIndexer.exe', 'DiagTrackRunner.exe', 'WINWORD.EXE', 'MFPlayback.exe',
             'WinRAR.exe', 'svchost.exe', 'wmpnetwk.exe',
             'IntelSoftwareAssetManagerService.exe', 'VBoxService.exe', 'Explorer.EXE',
             'powershell.exe', 'wsqmcons.exe', 'System', 'EXCEL.EXE', 'sppsvc.exe',
             'compattelrunner.exe', 'taskeng.exe', 'PT-BulletPhysics64.exe', 'steam.exe',
             'soffice.bin', 'VBoxTray.exe', 'lsm.exe', 'Cobian.Reflector.Application.exe',
             '7zG.exe', 'taskhost.exe', 'schtasks.exe', 'SearchProtocolHost.exe',
             'PT-CPUTest64.exe', 'AxCrypt.exe'],
        'test_processes': ['GoogleCrashHandler64.exe', 'DllHost.exe', 'AUDIODG.EXE', 'wmiprvse.exe',
                           'WordProcessing.exe', 'cmd.exe', 'sc.exe', 'csrss.exe', 'lame.exe', 'NativeApp.exe',
                           'DeviceDisplayObjectProvider.exe', 'spoolsv.exe', 'WMIADAP.EXE']
    },
    {
        'train_processes': ['SearchIndexer.exe', 'DllHost.exe', 'IntelSoftwareAssetManagerService.exe',
             'spoolsv.exe', 'SearchFilterHost.exe', 'csrss.exe', 'VBoxService.exe',
             'helper.exe', 'MFVideoChat2.exe', 'DeviceDisplayObjectProvider.exe',
             'Dwm.exe', 'CompatTelRunner.exe', 'wsqmcons.exe', 'smss.exe', 'Idle',
             'conhost.exe', 'MFPlayback.exe', 'libreofficeCalcTest.exe', 'sc.exe',
             'AUDIODG.EXE', 'wmpnetwk.exe', 'PerformanceTest64.exe',
             'Cobian.Reflector.Application.exe', 'sdclt.exe', 'WinRAR.exe', 'taskeng.exe',
             'curl.exe', 'Browsing.exe', '7zG.exe', 'GoogleCrashHandler64.exe',
             'PT-CPUTest64.exe', 'EXCEL.EXE', 'VBoxTray.exe', 'WMIADAP.EXE',
             'WordProcessing.exe', 'SearchProtocolHost.exe', 'WINWORD.EXE', 'lsass.exe',
             'wininit.exe', 'powershell.exe', 'ffmpeg.exe', 'lame.exe', 'winlogon.exe',
             'GoogleCrashHandler.exe', 'steam.exe', 'services.exe', 'AxCrypt.exe',
             'lsm.exe', 'compattelrunner.exe'],
        'test_processes': ['Explorer.EXE', 'DiagTrackRunner.exe', 'taskhost.exe', 'wmiprvse.exe', 'sppsvc.exe', 'System', 'cmd.exe', 'NativeApp.exe', 'GoogleUpdate.exe', 'svchost.exe', 'schtasks.exe', 'soffice.bin', 'PT-BulletPhysics64.exe']
    }
]
